---

- hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: "update all packages"
      yum:
        name: "*"
        state: latest

    - name: "Basic LAMP server"
      yum:
        name:
          - httpd
          - mariadb
          - mariadb-server
          - epel-release
          - php-gd
          - php-imap
          - php-xml
          - php-mbstring
          - php-intl
          - php-pecl-apcu
        state: present

    - name: "Start service httpd, mariadb if not started"
      ansible.builtin.service: "name={{ item }}"
      with_items:
        - httpd
        - mariadb