---
- hosts: centos7
  gather_facts: yes
  become: yes

  tasks:
   - name: Install Apache
     yum:
      name: httpd
   - name: permit traffic in default zone for https service
     firewalld:
        service: https
        permanent: yes
        state: enabled
   - name: permit traffic in default zone for http service
     firewalld:
        service: http
        permanent: yes
        state: enabled
   - name: reload service firewalld
     systemd:
        name: firewalld
        state: reload
   - name: Make sure Apache is stated now and boot.
     service: name=httpd state=started enable=yes

      
