---
- hosts: centos7
  gather_facts: yes
  become: yes

  tasks:
   - name: Install Apache
     yum:
      name: httpd
   - name: permit traffic in default zone for https service
     firewalld:
        service: https
        permanent: yes
        state: enabled
   - name: permit traffic in default zone for http service
     firewalld:
        service: http
        permanent: yes
        state: enabled
   - name: Start service httpd, if not started
     service:
       name: httpd
       state: started

          
